name: Pi kernel build and publish APT repo

on:
  push:
    branches: ["rpi-*"]
  workflow_dispatch:

env:
  NUM_JOBS: 6

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        include:
          - name: bcm2711
            arch: arm64
            defconfig: bcm2711_defconfig
            kernel: kernel8
    outputs:
      kernel_version: ${{ steps.kernel_version.outputs.version_string }}

    steps:
      - name: apt-get update
        run: |
          sudo apt-get update

      - name: Install armhf crossbuild toolchain
        if: matrix.arch == 'arm'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install -y gcc-arm-linux-gnueabihf
        timeout-minutes: 15

      - name: Install ccache
        run: sudo apt-get install -y ccache

      - name: Set up ccache cache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ matrix.name }}-ccache-${{ hashFiles('**/.config') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.name }}-ccache-
            ${{ runner.os }}-ccache-
            ${{ runner.os }}-
            ccache-

      - name: Reset ccache statistics
        run: ccache -z

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: true

      - name: Build kernel ${{matrix.name}}
        run: |
          mkdir ${{github.workspace}}/build
          export ARCH=${{matrix.arch}}
          if [[ "$ARCH" == "arm64" ]]; then
            export DTS_SUBDIR=broadcom
            export IMAGE=Image.gz
          else
            export CROSS_COMPILE=arm-linux-gnueabihf-
            export DTS_SUBDIR=broadcom
            export IMAGE=zImage
          fi
          make O=${{github.workspace}}/build ${{matrix.defconfig}}

          scripts/config --file ${{github.workspace}}/build/.config --disable CONFIG_ARM64_VA_BITS_39
          scripts/config --file ${{github.workspace}}/build/.config --enable CONFIG_ARM64_VA_BITS_48
          scripts/config --file ${{github.workspace}}/build/.config --set-val ARM64_VA_BITS 48
          scripts/config --file ${{github.workspace}}/build/.config --set-val PGTABLE_LEVELS 4
          # scripts/config --file ${{github.workspace}}/build/.config --set-val CONFIG_WERROR y
          scripts/config --file ${{github.workspace}}/build/.config --set-val CONFIG_LOCALVERSION -v8-${{github.run_number}}-custom-for-envoy

          make O=${{github.workspace}}/build -j ${{env.NUM_JOBS}} $IMAGE modules dtbs
          make O=${{github.workspace}}/build -j ${{env.NUM_JOBS}} bindeb-pkg

      - name: Get kernel version string
        id: kernel_version
        run: |
          VERSION=$(make -s -C ${{github.workspace}}/build kernelrelease)
          echo "version_string=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload .deb packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.name}}_pkgs
          path: ${{github.workspace}}/*.deb
          retention-days: 5

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Check out gh-pages branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download .deb packages
        uses: actions/download-artifact@v4
        with:
          name: bcm2711_pkgs
          path: ./bcm2711_pkgs

      - name: Update APT Repository
        run: |
          cd gh-pages
          REPO_DIR="dists/stable/main/binary-arm64"
          mkdir -p "$REPO_DIR"
          mv ../bcm2711_pkgs/*.deb "$REPO_DIR/"

          cd "$REPO_DIR"
          dpkg-scanpackages . /dev/null > Packages
          gzip -k -f Packages
          cd gh-pages/dists/stable

          apt-ftparchive release . > Release
          gpg --clearsign -o InRelease Release


          gpg --export --armor "Raspberry Pi Kernel for Envoy" >  > public.key

      - name: Commit and Push to gh-pages
        run: |
          cd gh-pages
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update APT repository with kernel ${{ needs.build.outputs.kernel_version_string }}" || echo "No changes to commit"
          git push origin gh-pages
