name: Pi kernel build tests

on:
  push:
    branches: ["rpi-*"]
  workflow_dispatch:

env:
  NUM_JOBS: 6

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        include:
          - name: bcm2711
            arch: arm64
            defconfig: bcm2711_defconfig
            kernel: kernel8
    outputs:
      kernel: ${{ steps.kernel_version.outputs.tag_name }}
    steps:
      - name: Install armhf crossbuild toolchain
        if: matrix.arch == 'arm'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf
        timeout-minutes: 15

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: true

      - name: Build kernel ${{matrix.name}}
        run: |
          mkdir ${{github.workspace}}/build
          export ARCH=${{matrix.arch}}
          if [[ "$ARCH" == "arm64" ]]; then
            export DTS_SUBDIR=broadcom
            export IMAGE=Image.gz
          else
            export CROSS_COMPILE=arm-linux-gnueabihf-
            export DTS_SUBDIR=broadcom
            export IMAGE=zImage
          fi
          make O=${{github.workspace}}/build ${{matrix.defconfig}}

          scripts/config --file ${{github.workspace}}/build/.config --disable CONFIG_ARM64_VA_BITS_39
          scripts/config --file ${{github.workspace}}/build/.config --enable CONFIG_ARM64_VA_BITS_48
          scripts/config --file ${{github.workspace}}/build/.config --set-val ARM64_VA_BITS 48
          scripts/config --file ${{github.workspace}}/build/.config --set-val PGTABLE_LEVELS 4
          scripts/config --file ${{github.workspace}}/build/.config --set-val CONFIG_LOCALVERSION -v8-${{github.run_number}}-custom-for-envoy
          scripts/config --file ${{github.workspace}}/build/.config --set-val CONFIG_WERROR y

          make O=${{github.workspace}}/build -j ${{env.NUM_JOBS}} $IMAGE modules dtbs
          make O=${{github.workspace}}/build -j ${{env.NUM_JOBS}} LOCALVERSION=-v8-${{github.run_number}}-custom-for-envoy bindeb-pkg

      - name: Tar build
        run: tar -cvf ${{matrix.name}}_build.tar -C ${{github.workspace}}/install .

      - name: Get kernel version
        id: kernel_version
        run: echo "tag_name=$(make -s -C ${{github.workspace}}/build kernelrelease)" >> $GITHUB_OUTPUT

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.name}}_build
          path: ${{matrix.name}}_build.tar
          retention-days: 90

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: switch to gh-pages branch
        run: git switch -c gh-pages

      - name: create repo dir
        run: |
          mkdir -p dists/stable/main/binary-arm64
          rm -rf dists/stable/main/binary-arm64/* || true

      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: bcm2711_build
          path: ./bcm2711_build

      - name: extract and create Packages.gz
        run: |
          tar -xvf ./bcm2711_build/bcm2711_build.tar -C dists/stable/main/binary-arm64
          cd dists/stable/main/binary-arm64
          dpkg-scanpackages . /dev/null > Packages
          gzip -k -f Packages

      - name: create Release and InRelease files
        run: |
          cd dists/stable
          apt-ftparchive release . > Release
          gpg --clearsign -o InRelease Release

      - name: put GPG public key
        run: |
          gpg --export --armor "Raspberry Pi Kernel for Envoy" > Raspberry_Pi_Kernel_for_Envoy.gpg

      - name: rm
        run: rm -rf bcm2711_build

      - name: push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update APT repository with kernel ${{ needs.build.outputs.kernel }}"
          git push origin gh-pages
