name: Pi kernel build and publish APT repo

on:
  push:
    branches: ["rpi-*"]
  workflow_dispatch:

env:
  NUM_JOBS: 6
  CCACHE_DIR: ~/.ccache
  CCACHE_MAXSIZE: 10G

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        include:
          - name: bcm2711
            arch: arm64
            defconfig: bcm2711_defconfig
            kernel: kernel8
    outputs:
      kernel_version: ${{ steps.kernel_version.outputs.version_string }}

    steps:
      - name: Install armhf crossbuild toolchain
        if: matrix.arch == 'arm'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get install -y gcc-arm-linux-gnueabihf
        timeout-minutes: 15

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ccache \
            bc \
            bison \
            flex \
            libssl-dev \
            make \
            libc6-dev \
            libncurses5-dev \
            rsync \
            build-essential \
            dpkg-dev \
            libelf-dev \
            debhelper

      - name: Set up ccache cache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ matrix.name }}-ccache-${{ hashFiles('**/.config') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.name }}-ccache-
            ${{ runner.os }}-ccache-
            ${{ runner.os }}-
            ccache-

      - name: Reset ccache statistics
        run: ccache -z

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: true

      - name: Prepare build directory
        run: mkdir ${{github.workspace}}/build

      - name: Set environment variables
        id: env_vars
        run: |
          echo "ARCH=${{matrix.arch}}" >> $GITHUB_ENV
          if [[ "${{matrix.arch}}" == "arm64" ]]; then
            echo "DTS_SUBDIR=broadcom" >> $GITHUB_ENV
            echo "IMAGE=Image.gz" >> $GITHUB_ENV
          else
            echo "CROSS_COMPILE=arm-linux-gnueabihf-" >> $GITHUB_ENV
            echo "DTS_SUBDIR=broadcom" >> $GITHUB_ENV
            echo "IMAGE=zImage" >> $GITHUB_ENV
          fi

      - name: Kernel defconfig
        run: make O=${{github.workspace}}/build ${{matrix.defconfig}}

      - name: Kernel config customization
        run: |
          scripts/config --file ${{github.workspace}}/build/.config --disable CONFIG_ARM64_VA_BITS_39
          scripts/config --file ${{github.workspace}}/build/.config --enable CONFIG_ARM64_VA_BITS_48
          scripts/config --file ${{github.workspace}}/build/.config --set-val ARM64_VA_BITS 48
          scripts/config --file ${{github.workspace}}/build/.config --set-val PGTABLE_LEVELS 4
          scripts/config --file ${{github.workspace}}/build/.config --set-val CONFIG_LOCALVERSION -v8-${{github.run_number}}-custom-for-envoy

      - name: Build kernel image, modules, dtbs
        run: make CC="ccache gcc" O=${{github.workspace}}/build -j ${{env.NUM_JOBS}} ${{ env.IMAGE }} modules dtbs

      - name: Build kernel deb packages
        run: make CC="ccache gcc" O=${{github.workspace}}/build -j ${{env.NUM_JOBS}} LOCALVERSION="-v8-${{github.run_number}}-custom-for-envoy" bindeb-pkg

      - name: Get kernel version string
        id: kernel_version
        run: |
          VERSION=$(make -s -C ${{github.workspace}}/build kernelrelease)
          echo "version_string=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload .deb packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.name}}_pkgs
          path: ${{github.workspace}}/*.deb
          retention-days: 5

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Check out gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download .deb packages
        uses: actions/download-artifact@v4
        with:
          name: bcm2711_pkgs
          path: ./bcm2711_pkgs

      - name: Move .deb packages to repo directory
        run: |
          cd gh-pages
          mkdir -p dists/stable/main/binary-arm64
          mv ../bcm2711_pkgs/*.deb dists/stable/main/binary-arm64/

      - name: Update Packages index
        run: |
          cd gh-pages/dists/stable/main/binary-arm64
          dpkg-scanpackages . /dev/null > Packages
          gzip -k -f Packages

      - name: Update Release file and sign
        run: |
          cat << EOF > ~/apt-ftparchive.conf
          APT::FTPArchive::Release {
            Origin "walnuts1018";
            Label "Raspberry Pi Kernel for Envoy";
            Suite "stable";
            Codename "stable";
            Architectures "arm64";
            Components "main";
            Description "Custom kernel repository for Envoy on Raspberry Pi";
          };
          EOF

          cd gh-pages/dists/stable
          apt-ftparchive -c ~/apt-ftparchive.conf release . > Release
          gpg --batch --yes --passphrase ${{ secrets.GPG_PASSPHRASE }} --clearsign -o InRelease Release

      - name: Export GPG public key
        run: |
          cd gh-pages
          gpg --export --armor "0172E98C9B6B9E859597CE1D71DCBD6F02535F2B" > public.key

      - name: Commit and Push to gh-pages
        run: |
          cd gh-pages
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update APT repository with kernel ${{ needs.build.outputs.kernel_version }}" || echo "No changes to commit"
          git push origin gh-pages
